// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlMOUVJKTmBlxUjhGpLk82-XxUQvsQv50',
    appId: '1:1026545670025:web:da284ae27bbbf6da017358',
    messagingSenderId: '1026545670025',
    projectId: 'farm-535d5',
    authDomain: 'farm-535d5.firebaseapp.com',
    storageBucket: 'farm-535d5.firebasestorage.app',
    measurementId: 'G-L6H1GB50VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMHeNUrbEI1erb_W0Nqd2x9FuHJKUuok',
    appId: '1:1026545670025:android:ccf7e663863ecdb4017358',
    messagingSenderId: '1026545670025',
    projectId: 'farm-535d5',
    storageBucket: 'farm-535d5.firebasestorage.app',
  );
}
